### ISSUE TITLE
Set user not working

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/node-homey-log#3]
https://github.com/athombv/node-homey-log#logsetuser-object-user-

When using the set user with an object like, for example:
Log.setUser('4d5fbee2-8749-427c-ac57-ae83de19533a');

Sentry reports an error:

![image](https://user-images.githubusercontent.com/15921016/31384826-f29d10b2-adc0-11e7-9c16-340219e11050.png)

**Comment by joachimroeleveld** [comment]
Please reopen if you still encounter issues.
